export const VISIT_TYPES = [
    { code: "PTE",  name: "Physical Therapist Evaluation",                    discipline: "Physical Therapist", sortOrder: 1, isEvaluation: true },
    { code: "PTF",  name: "Physical Therapist Follow-up Visit",                discipline: "Physical Therapist", sortOrder: 2 },
    { code: "PTDC", name: "Physical Therapist Discharge",                      discipline: "Physical Therapist", sortOrder: 3 },
    { code: "PTDN", name: "Physical Therapist Discharge Note (Non-Billable)",  discipline: "Physical Therapist", sortOrder: 4 },
    { code: "PTEO", name: "Physical Therapist Eval Oasis",                     discipline: "Physical Therapist", sortOrder: 5, isEvaluation: true },
    { code: "PTDO", name: "Physical Therapist Discharge Oasis",                discipline: "Physical Therapist", sortOrder: 6 },
    { code: "PTAV", name: "Physical Therapist Attempted Visit",                discipline: "Physical Therapist", sortOrder: 7 },
    { code: "PTR",  name: "Physical Therapist Reassessment",                   discipline: "Physical Therapist", sortOrder: 8 },
    { code: "PTSU", name: "Physical Therapist Supervisory",                    discipline: "Physical Therapist", sortOrder: 9 },
    { code: "PTFA", name: "Physical Therapist Assistant Follow-up Visit",      discipline: "Physical Therapist", sortOrder: 10 },

    { code: "OTE",  name: "Occupational Therapist Evaluation",                 discipline: "Occupational Therapist", sortOrder: 1, isEvaluation: true },
    { code: "OTF",  name: "Occupational Therapist Follow-up Visit",            discipline: "Occupational Therapist", sortOrder: 2 },
    { code: "OTDC", name: "Occupational Therapist Discharged",                 discipline: "Occupational Therapist", sortOrder: 3 },
    { code: "OTDN", name: "Occupational Therapist Discharge Note (Non-Billable)", discipline: "Occupational Therapist", sortOrder: 4 },
    { code: "OTEO", name: "Occupational Therapist Eval Oasis",                 discipline: "Occupational Therapist", sortOrder: 5, isEvaluation: true },
    { code: "OTDO", name: "Occupational Therapist Discharge Oasis",            discipline: "Occupational Therapist", sortOrder: 6 },
    { code: "OTAV", name: "Occupational Therapist Attempted Visit",            discipline: "Occupational Therapist", sortOrder: 7 },
    { code: "OTR",  name: "Occupational Therapist Reassessment",               discipline: "Occupational Therapist", sortOrder: 8 },
    { code: "OTSU", name: "Occupational Therapist Supervisory",                discipline: "Occupational Therapist", sortOrder: 9 },
    { code: "OTFA", name: "Occupational Therapist Assistant Follow-up Visit",  discipline: "Occupational Therapist", sortOrder: 10 },

    { code: "STE",  name: "Speech Therapist Evaluation",                       discipline: "Speech Therapist", sortOrder: 1, isEvaluation: true },
    { code: "STF",  name: "Speech Therapist Follow-up Visit",                  discipline: "Speech Therapist", sortOrder: 2 },
    { code: "STDC", name: "Speech Therapist Discharged",                       discipline: "Speech Therapist", sortOrder: 3 },
    { code: "STDN", name: "Speech Therapist Discharge Note (Non-Billable)",    discipline: "Speech Therapist", sortOrder: 4 },
    { code: "STEO", name: "Speech Therapist Eval Oasis",                       discipline: "Speech Therapist", sortOrder: 5, isEvaluation: true },
    { code: "STDO", name: "Speech Therapist Discharged Oasis",                 discipline: "Speech Therapist", sortOrder: 6 },
    { code: "STAV", name: "Speech Therapist Attempted Visit",                  discipline: "Speech Therapist", sortOrder: 7 },
    { code: "STR",  name: "Speech Therapist Reassessment",                     discipline: "Speech Therapist", sortOrder: 8 },

    { code: "MV", name: "Missed Visit", discipline: "All", sortOrder: 99 },
    { code: "CN", name: "Communication Note", discipline: "All", sortOrder: 100 },
];
