ALTER TABLE "customer_profiles" DROP CONSTRAINT "customer_profiles_user_id_fkey";
ALTER TABLE "therapist_profiles" DROP CONSTRAINT "therapist_profiles_user_id_fkey";
ALTER TABLE "patients" DROP CONSTRAINT "patients_user_id_fkey";
ALTER TABLE "license_documents" DROP CONSTRAINT "license_documents_user_id_fkey";
ALTER TABLE "license_documents" DROP CONSTRAINT "license_documents_verified_by_fkey";
ALTER TABLE "disputes" DROP CONSTRAINT "disputes_user_id_fkey";
ALTER TABLE "disputes" DROP CONSTRAINT "disputes_assigned_admin_id_fkey";
ALTER TABLE "notifications" DROP CONSTRAINT "notifications_user_id_fkey";
ALTER TABLE "sub_admin_profiles" DROP CONSTRAINT "sub_admin_profiles_user_id_fkey";
ALTER TABLE "sub_admin_profiles" DROP CONSTRAINT "sub_admin_profiles_created_by_admin_id_fkey";
ALTER TABLE "commission_configs" DROP CONSTRAINT "commission_configs_created_by_admin_id_fkey";
ALTER TABLE "audit_logs" DROP CONSTRAINT "audit_logs_actor_id_fkey";
ALTER TABLE "direct_conversations" DROP CONSTRAINT "direct_conversations_user1_id_fkey";
ALTER TABLE "direct_conversations" DROP CONSTRAINT "direct_conversations_user2_id_fkey";
ALTER TABLE "messages" DROP CONSTRAINT "messages_sender_id_fkey";
ALTER TABLE "messages" DROP CONSTRAINT "messages_recipient_id_fkey";
ALTER TABLE "message_attachments" DROP CONSTRAINT "message_attachments_uploaded_by_id_fkey";
ALTER TABLE "system_config" DROP CONSTRAINT "system_config_updated_by_fkey";

ALTER TABLE "users" ALTER COLUMN "id" TYPE VARCHAR(128);
ALTER TABLE "customer_profiles" ALTER COLUMN "user_id" TYPE VARCHAR(128);
ALTER TABLE "therapist_profiles" ALTER COLUMN "user_id" TYPE VARCHAR(128);
ALTER TABLE "patients" ALTER COLUMN "user_id" TYPE VARCHAR(128);
ALTER TABLE "license_documents" ALTER COLUMN "user_id" TYPE VARCHAR(128);
ALTER TABLE "license_documents" ALTER COLUMN "verified_by" TYPE VARCHAR(128);
ALTER TABLE "disputes" ALTER COLUMN "user_id" TYPE VARCHAR(128);
ALTER TABLE "disputes" ALTER COLUMN "assigned_admin_id" TYPE VARCHAR(128);
ALTER TABLE "notifications" ALTER COLUMN "user_id" TYPE VARCHAR(128);
ALTER TABLE "sub_admin_profiles" ALTER COLUMN "user_id" TYPE VARCHAR(128);
ALTER TABLE "sub_admin_profiles" ALTER COLUMN "created_by_admin_id" TYPE VARCHAR(128);
ALTER TABLE "commission_configs" ALTER COLUMN "created_by_admin_id" TYPE VARCHAR(128);
ALTER TABLE "audit_logs" ALTER COLUMN "actor_id" TYPE VARCHAR(128);
ALTER TABLE "direct_conversations" ALTER COLUMN "user1_id" TYPE VARCHAR(128);
ALTER TABLE "direct_conversations" ALTER COLUMN "user2_id" TYPE VARCHAR(128);
ALTER TABLE "messages" ALTER COLUMN "sender_id" TYPE VARCHAR(128);
ALTER TABLE "messages" ALTER COLUMN "recipient_id" TYPE VARCHAR(128);
ALTER TABLE "message_attachments" ALTER COLUMN "uploaded_by_id" TYPE VARCHAR(128);
ALTER TABLE "system_config" ALTER COLUMN "updated_by" TYPE VARCHAR(128);

ALTER TABLE "customer_profiles" ADD CONSTRAINT "customer_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "therapist_profiles" ADD CONSTRAINT "therapist_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "patients" ADD CONSTRAINT "patients_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "license_documents" ADD CONSTRAINT "license_documents_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "license_documents" ADD CONSTRAINT "license_documents_verified_by_fkey" FOREIGN KEY ("verified_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "disputes" ADD CONSTRAINT "disputes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "disputes" ADD CONSTRAINT "disputes_assigned_admin_id_fkey" FOREIGN KEY ("assigned_admin_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "sub_admin_profiles" ADD CONSTRAINT "sub_admin_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "sub_admin_profiles" ADD CONSTRAINT "sub_admin_profiles_created_by_admin_id_fkey" FOREIGN KEY ("created_by_admin_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "commission_configs" ADD CONSTRAINT "commission_configs_created_by_admin_id_fkey" FOREIGN KEY ("created_by_admin_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_actor_id_fkey" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "direct_conversations" ADD CONSTRAINT "direct_conversations_user1_id_fkey" FOREIGN KEY ("user1_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "direct_conversations" ADD CONSTRAINT "direct_conversations_user2_id_fkey" FOREIGN KEY ("user2_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "messages" ADD CONSTRAINT "messages_sender_id_fkey" FOREIGN KEY ("sender_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "messages" ADD CONSTRAINT "messages_recipient_id_fkey" FOREIGN KEY ("recipient_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "message_attachments" ADD CONSTRAINT "message_attachments_uploaded_by_id_fkey" FOREIGN KEY ("uploaded_by_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "system_config" ADD CONSTRAINT "system_config_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
